MYSQL_URL = '//root:root@mysql-ad-v3-server-dev:3306/ad_reporting_system_v3_dev?charset=utf8mb4'
MYSQL_URL = '//root:root@0.0.0.0:3310/ad_reporting_system_v3_dev?charset=utf8mb4'
REDIS_HOST = 'redis-ad-v3-server-dev'
REDIS_PORT = '6379'
LOCAL_TZ = 'Asia/Taipei'
