"""生成測試資料表

Revision ID: 1bdf93438f91
Revises: 
Create Date: 2023-07-10 18:43:50.658058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bdf93438f91'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='2023-07-10 18:43:50', nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='2023-07-10 18:43:50', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_table_name'), 'test_table', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_table_name'), table_name='test_table')
    op.drop_table('test_table')
    # ### end Alembic commands ###
