"""老K測試

Revision ID: 1d47756db72b
Revises: 1bdf93438f91
Create Date: 2023-07-12 11:54:26.486436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d47756db72b'
down_revision = '1bdf93438f91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_table', sa.Column('is_online', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_table', 'is_online')
    # ### end Alembic commands ###
